# Generated by Django 4.1.6 on 2023-02-06 19:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mood', models.CharField(choices=[('Very sad', 'Very Sad'), ('Sad', 'Sad'), ('Ok', 'Ok'), ('Happy', 'Happy'), ('Very Happy', 'Very Happy')], default='Ok', max_length=20)),
                ('rate_one', models.IntegerField(blank=True, null=True)),
                ('question_one', models.CharField(max_length=300)),
                ('rate_two', models.IntegerField(blank=True, null=True)),
                ('question_two', models.CharField(max_length=300)),
                ('rate_tree', models.IntegerField(blank=True, null=True)),
                ('question_tree', models.CharField(max_length=300)),
                ('created_at', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moods', to='users.user')),
            ],
        ),
    ]
