# Generated by Django 4.1.6 on 2023-02-07 14:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("moods", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mood",
            name="created_at",
        ),
    ]
