# Generated by Django 4.1.6 on 2023-02-08 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moods', '0003_mood_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mood',
            name='mood',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
