# Generated by Django 4.1.6 on 2023-02-07 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thoughts', '0003_thought_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thought',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
